name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches: ["master"]  # ou "main", se for o caso

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish Blazor WebAssembly app
        run: dotnet publish -c Release -o release

      - name: Fix base href for GitHub Pages
        run: |
          sed -i 's|<base href="/"|<base href="/linconclass-blazor-site/"|' release/wwwroot/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./release/wwwroot
