name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: ["master"] # Seu branch principal
  workflow_dispatch:

# Define permissões para o deploy
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (Pegar o código)
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          # Sua versão .NET 10.0 (Prévia)
          dotnet-version: '10.0.x' 

      - name: Restore and Publish Blazor WASM
        # Compila o projeto na pasta 'linconclass'
        # e joga a saída para a pasta 'dist'
        run: dotnet publish linconclass/linconclass.csproj -c Release -o dist

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # O caminho final dos arquivos estáticos é: pasta de saída / wwwroot
          # Onde o 'index.html' está
          path: 'dist/wwwroot'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
